# Generated by Django 5.0.2 on 2024-03-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='user_gmail',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
