# Generated by Django 5.0.2 on 2024-03-11 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.location'),
            preserve_default=False,
        ),
    ]
