# Generated by Django 5.0.2 on 2024-03-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_hotel_hotel_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
